name: moegyishop
description: An online e-commerce shopping app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  provider: ^6.0.5
  firebase_app_check: ^0.2.1+8
  image_picker: 1.1.2
  firebase_storage: ^11.6.0
  google_maps_flutter: ^2.5.3
  geocoding: ^2.2.0
  geolocator: ^11.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
