name: moegyishop
description: An online e-commerce shopping app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  cloud_firestore: ^6.0.1
  provider: ^6.0.5
  firebase_app_check: ^0.4.0+1
  image_picker: ^1.2.0
  firebase_storage: ^13.0.1
  google_maps_flutter: ^2.5.3
  geocoding: ^4.0.0
  geolocator: ^14.0.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
