name: moegyishop
description: An online e-commerce shopping app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core:
  firebase_auth:
  cloud_firestore:
  provider:
  firebase_app_check:
  image_picker:
  firebase_storage:
  google_maps_flutter:
  geocoding:
  geolocator:
  permission_handler:
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
