// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPu30SDETczr7gOjNSglDSHWYbMCuEnW4',
    appId: '1:271385741888:web:db61655eda0589190b6da5',
    messagingSenderId: '271385741888',
    projectId: 'moegyishop-820a2',
    authDomain: 'moegyishop-820a2.firebaseapp.com',
    storageBucket: 'moegyishop-820a2.firebasestorage.app',
    measurementId: 'G-VS27D5VG60',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-NvAQYtytzNWy0d2y95f6Q1xVec-4n-w',
    appId: '1:271385741888:android:ff4d18d8e25555530b6da5',
    messagingSenderId: '271385741888',
    projectId: 'moegyishop-820a2',
    storageBucket: 'moegyishop-820a2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPkDyA-qiDIFYNcJ_6otmz_924mr1X6Gk',
    appId: '1:271385741888:ios:cdd08ec7f577a0500b6da5',
    messagingSenderId: '271385741888',
    projectId: 'moegyishop-820a2',
    storageBucket: 'moegyishop-820a2.firebasestorage.app',
    iosBundleId: 'com.moegyi.shop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPkDyA-qiDIFYNcJ_6otmz_924mr1X6Gk',
    appId: '1:271385741888:ios:cdd08ec7f577a0500b6da5',
    messagingSenderId: '271385741888',
    projectId: 'moegyishop-820a2',
    storageBucket: 'moegyishop-820a2.firebasestorage.app',
    iosBundleId: 'com.moegyi.shop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPu30SDETczr7gOjNSglDSHWYbMCuEnW4',
    appId: '1:271385741888:web:5dbd483d33e613cf0b6da5',
    messagingSenderId: '271385741888',
    projectId: 'moegyishop-820a2',
    authDomain: 'moegyishop-820a2.firebaseapp.com',
    storageBucket: 'moegyishop-820a2.firebasestorage.app',
    measurementId: 'G-3XXE6JDK2V',
  );

}